---
# Practicalli Git
site_name: Practicalli Git
site_url: https://practical.li/git
site_description: Practical guide to distributed version control with Git
site_author: Practicalli
site_org: https://practical.li/
copyright: Copyright &copy 2023  Practicali <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
repo_url: https://github.com/practicalli/git/
edit_uri: https://github.com/practicalli/git/edit/main/docs/

# Deployment
# remote_name: origin
remote_branch: gh-pages # deployment branch

# Theme and styling
theme:
  name: material
  logo: assets/images/practicalli-logo.png
  favicon: assets/favicon.svg
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes # Nav sections can have files
    - navigation.instant # Avoid page reloading for internal links
    - navigation.top
    - navigation.tracking # Update URL with sub-heading anchor names
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Override theme
  custom_dir: overrides

extra_css:
  - assets/stylesheets/extra.css

## Additional styling
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html # Grids
  - footnotes # footnotes and abbreviations
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys # keyboard keys
  - pymdownx.magiclink
  - def_list # lists
  - pymdownx.tasklist:
      custom_checkbox: true # checkboxes
  - toc:
      permalink: λ︎

## Plugins
plugins:
  # Explicitly add search plugin when defining plugins in this configuration file
  - search
  - callouts
  - glightbox # Image aligning
  - git-revision-date-localized: # Update and Creation date of each page
      # enable_creation_date: true
      fallback_to_build_date: true

  # Generate Social Cards via CI only
  # in assets/images/social
  - social:
      cards: !ENV [MKDOCS_SOCIAL_CARDS_GENERATE, true]

  # Redirect pages when moved or changed
  # - redirects:
  #     redirect_maps:
  #       repl-driven-development.md: introduction/repl-workflow.md

# Footer / Social Media
extra:
  analytics:
    provider: google
    property: G-2EC8XDXP0L
  social:
    - icon: material/web
      link: https://practical.li/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jr0cket/
    - icon: fontawesome/brands/slack
      link: https://clojurians.slack.com/messages/practicalli
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/practical_li
    - icon: fontawesome/brands/github
      link: https://github.com/practicalli
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/practicalli

# Navigation
nav:
  - Introduction:
      - index.md
      - Git Workflow: introduction/repl-workflow.md
      - Git Cheatsheet: introduction/cheatsheet.md
      - Concepts: introduction/concepts.md
      - Contributing: https://practical.li/contributing/
      - Writing Tips: https://practical.li/writing-tips/
  - Install:
      - install/index.md
      - Configure: install/configure.md
  - Staging:
      - staging/index.md
      - Use the Index: using-stages/use-the-index.md
      - Use git diff: using-stages/use-git-diff.md
      - Interactive staging: using-stages/interactive-staging.md
  - Commits:
      - commits/index.md
      - Messages: commits/messages.md
      - Commit often: commits/commit-often.md
      - Amend: commits/amend.md
      - Squash: commits/squash.md
  - History:
      - history/index.md
      - Magit Git Log: history/magit-git-log.md
      - Track commits: history/track-commits.md
      - Blame: blame.md
  - Rebasing:
      - rebasing/index.md
      - local repositories: rebasing/index.md
  - Ignoring files:
      - ignoring-files/index.md
  - Global Ignore: ignoring-files/global-ignore.md
